from __future__ import annotations

import math
from functools import lru_cache
from typing import Tuple

import numpy as np
from scipy.linalg import eigh


def tmsv_state_vector(Ns: float, cutoff: int) -> np.ndarray:
    """Truncated TMSV |psi> = sum_n sqrt(p_n) |n,n> with renormalization."""
    lam = Ns / (Ns + 1.0)
    coeff = np.array([np.sqrt((1.0 - lam) * lam**n) for n in range(cutoff)], dtype=complex)
    coeff /= np.linalg.norm(coeff)
    vec = np.zeros(cutoff * cutoff, dtype=complex)
    for n, c in enumerate(coeff):
        vec[n * cutoff + n] = c
    return vec


def tmsv_tail_probability(Ns: float, cutoff: int) -> float:
    lam = Ns / (Ns + 1.0)
    return float(lam**cutoff)


@lru_cache(maxsize=128)
def loss_kraus_single(cutoff: int, eta: float) -> Tuple[np.ndarray, ...]:
    """Photon-loss Kraus operators for a single truncated mode."""
    eta = float(eta)
    ops = []
    for lost in range(cutoff):
        K = np.zeros((cutoff, cutoff), dtype=complex)
        for n in range(lost, cutoff):
            amp = math.sqrt(math.comb(n, lost)) * ((1.0 - eta) ** (lost / 2.0)) * (eta ** ((n - lost) / 2.0))
            K[n - lost, n] = amp
        ops.append(K)
    return tuple(ops)


def apply_two_mode_loss(rho: np.ndarray, cutoff: int, eta_s: float, eta_i: float) -> np.ndarray:
    """Apply independent signal and idler loss using tensor contractions.

    This avoids explicit two-mode Kronecker Kraus matrices and is much faster
    for repeated parameter scans. The density tensor is ordered as
    rho[signal, idler, signal_prime, idler_prime].
    """
    Ks = loss_kraus_single(cutoff, float(eta_s))
    Ki = loss_kraus_single(cutoff, float(eta_i))
    R = rho.reshape(cutoff, cutoff, cutoff, cutoff)

    # Signal channel: out[s,i,t,j] = sum_l,a,b K_l[s,a] R[a,i,b,j] K_l^*[t,b]
    Rs = np.zeros_like(R, dtype=complex)
    for A in Ks:
        Rs += np.einsum("sa,aibj,tb->sitj", A, R, A.conj(), optimize=True)

    # Idler channel: out[s,i,t,j] = sum_l,a,b K_l[i,a] Rs[s,a,t,b] K_l^*[j,b]
    Ri = np.zeros_like(Rs, dtype=complex)
    for B in Ki:
        Ri += np.einsum("ia,satb,jb->sitj", B, Rs, B.conj(), optimize=True)

    out = Ri.reshape(cutoff * cutoff, cutoff * cutoff)
    tr = np.trace(out).real
    if tr > 0:
        out /= tr
    return hermitize(out)


def apply_signal_phase_diffusion(rho: np.ndarray, cutoff: int, gamma: float) -> np.ndarray:
    """Signal-mode phase diffusion: rho_{ns,ni;ms,mi} *= exp[-Gamma/2 (ns-ms)^2]."""
    gamma = float(gamma)
    out = rho.copy().astype(complex)
    for ns in range(cutoff):
        for ni in range(cutoff):
            row = ns * cutoff + ni
            for ms in range(cutoff):
                factor = math.exp(-0.5 * gamma * (ns - ms) ** 2)
                col_start = ms * cutoff
                out[row, col_start:col_start + cutoff] *= factor
    return hermitize(out)


def apply_signal_phase_shift(rho: np.ndarray, cutoff: int, phi: float) -> np.ndarray:
    phases = np.zeros(cutoff * cutoff, dtype=complex)
    for ns in range(cutoff):
        for ni in range(cutoff):
            phases[ns * cutoff + ni] = np.exp(-1j * phi * ns)
    U = np.diag(phases)
    return U @ rho @ U.conj().T


def number_operator_signal(cutoff: int) -> np.ndarray:
    n = np.diag(np.arange(cutoff, dtype=float))
    return np.kron(n, np.eye(cutoff))


def prepare_noisy_tmsv_density(Ns: float, cutoff: int, eta_s: float, eta_i: float, gamma: float) -> np.ndarray:
    psi = tmsv_state_vector(Ns, cutoff)
    rho = np.outer(psi, psi.conj())
    rho = apply_two_mode_loss(rho, cutoff, eta_s, eta_i)
    if gamma != 0:
        rho = apply_signal_phase_diffusion(rho, cutoff, gamma)
    return hermitize(rho)


def qfi_unitary_generator(rho: np.ndarray, generator: np.ndarray, eig_tol: float = 1e-12) -> float:
    """QFI for phase generated by G: rho_phi = exp(-i phi G) rho exp(i phi G).

    Formula: F = 2 sum_{i,j} (li-lj)^2/(li+lj) |<i|G|j>|^2.
    """
    vals, vecs = eigh(hermitize(rho))
    vals = np.maximum(vals.real, 0.0)
    G_eig = vecs.conj().T @ generator @ vecs
    F = 0.0
    d = len(vals)
    for i in range(d):
        for j in range(d):
            denom = vals[i] + vals[j]
            if denom > eig_tol:
                F += 2.0 * ((vals[i] - vals[j]) ** 2) / denom * (abs(G_eig[i, j]) ** 2)
    return float(max(F.real, 0.0))


def hermitize(A: np.ndarray) -> np.ndarray:
    return 0.5 * (A + A.conj().T)
